// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package gittest contains autogenerated mocks.
package gittest

import "github.com/stretchr/testify/mock"
import "time"

// Cmd is an autogenerated mock type for the Cmd type
type Cmd struct {
	mock.Mock
}

// Run provides a mock function with given fields: args, timeout
func (mockerySelf *Cmd) Run(args []string, timeout time.Duration) (string, error) {
	ret := mockerySelf.Called(args, timeout)

	var r0 string
	if rf, ok := ret.Get(0).(func([]string, time.Duration) string); ok {
		r0 = rf(args, timeout)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, time.Duration) error); ok {
		r1 = rf(args, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
