// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package publishtest contains autogenerated mocks.
package publishtest

import "github.com/stretchr/testify/mock"

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: version
func (mockerySelf *Publisher) Publish(version string) error {
	ret := mockerySelf.Called(version)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
